import type { Metadata } from "next";
import { Cambay } from "next/font/google";
import "./globals.css";
import ToastProvider from "./provider/toastProvider";

const cambay = Cambay({
  subsets: ["latin"],
  weight: ["400", "700"],
  adjustFontFallback: false,
  variable: "--font-cambay",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${cambay} h-full antialiased`}
      suppressHydrationWarning 
    >
      <body className="min-h-screen flex flex-col">
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
